userpassword/userpassword/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from uspa import views

urlpatterns = [
	path('', views.index,name='index'),
	path('uspa/', include('uspa.urls')),
    path('admin/', admin.site.urls),
    path('logout/', views.userlogout,name='logout'),

]
 

userpassword/uspa/urls.py
from uspa import views
from django.urls import path

app_name = 'uspa'


urlpatterns = [
	path('register/', views.register,name='register'),
	path('user_login/', views.user_login,name='user_login'),
]

userpassword/uspa/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class userprofile(models.Model):

	user = models.OneToOneField(User,on_delete=models.CASCADE)

	#additional

	portfolio_site = models.URLField(blank=True)

	profile_pic = models.ImageField(upload_to = 'profile_pic',blank=True)


	def __str__(self):
		return self.user.username

userpassword/uspa/forms.py
from django import forms
from django.contrib.auth.models import User
from uspa.models import userprofile

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta():
		model = User
		fields = ('username','email','password')


class userprofileform(forms.ModelForm):
	class Meta():
		model = userprofile
		fields =('portfolio_site','profile_pic')

userpassword/uspa/views.py
from django.shortcuts import render
from uspa.forms import userprofileform,UserForm

#forlogin
from django.contrib.auth import authenticate,login,logout 
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required



# Create your views here.
def index(request):
	return render(request,'uspa/index.html')


@login_required
def special(request):
	return HttpResponse("You are logged in")



@login_required
def userlogout(request):
	logout(request)
	return HttpResponseRedirect(reverse('uspa:user_login'))




def register(request):
	
	registered=False

	if(request.method=='POST'):
		user_form = UserForm(data=request.POST)
		profile_form = userprofileform(data=request.POST)


		if(user_form.is_valid() or profile_form.is_valid()):

			user = user_form.save()
			user.set_password(user.password)#hashing the password
			user.save()

			profile =profile_form.save(commit=False)
			profile.user = user #sets up 121 relationship

			if 'profile_pic' in request.FILES:
				profile.profile_pic = request.FILES['profile_pic']

			profile.save()
			
			registered = True
		else:
			print(user_form.errors,profile_form.errors)
	else:
		user_form = UserForm()
		profile_form = userprofileform()

	return render(request,'uspa/Registration.html',
				{'user_form':user_form,'profile_form':profile_form,'registered':registered})					



def user_login(request):

	if request.method =='POST':
		username = request.POST.get('username')
		password = request.POST.get('password')


		user =authenticate(username=username,password=password)

		if user:
			if user.is_active:
				login(request,user)
				return HttpResponseRedirect(reverse('index'))

			else:
				return HttpResponse("ACCOUNT NOt ACTIVE")
		else:
			print("Someone tried to login and failed")
			print("Username: {} and password {}".format(username,password))
			return HttpResponse("Invalid login details supplied")

	else:
		return render(request,'uspa/login.html',{})

userpassword/templates/uspa/Registration.html
<!DOCTYPE html>
{%extends "uspa/base.html"%}
{%load static%}

{%block body_block%}
<div class="jumbotron">
{%if registered%}
	<h1>THANK YOU FOR REGISTRTING</h1>
{%else%}
<h1>Register here</h1>
<h3>fill the form</h3>

<form method="POST" enctype="multipart/form-data">
	<!-- enctype is for multimedia files -->
	{%csrf_token%}
	{{user_form.as_p}}
	{{profile_form.as_p}}
	<input type="submit" name="" value="Register">
</form>	

{%endif%}
</div>
{%endblock%}

userpassword/templates/uspa/base.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<title></title>
</head>
<body>
	<div class="navbar navbar-inverse" style="margin-bottom: 0px">
		<div class="container">
			<div class="navbar-brand"><a href="{%url 'index'%}"></a>Django</div>
			<ul class="nav navbar-nav">	
			<li class="navbar-link"><a href="{%url 'index'%}">HOME</a></li>	
            <li class="navbar-link"><a href="{%url 'admin:index'%}">Admin</a></li>
           <li class="navbar-link"><a href="{%url 'uspa:register'%}">Register</a></li>



           
        
        {% if user.is_authenticated%}   

		<li><a class="navbar-link" href="{%url 'logout'%}">logout</a></li>

		{%else%}

		 <li><a class="navbar-link"  href="{%url 'uspa:user_login'%}">Login</a></li>
		
		{% endif %}
			
		</div>
	</div>
	<div class="container">
	{%block body_block%}
	<h1>THIS ISMY BASE TEMPLATE</h1>
	<h2>ALL other templates will be like this only</h2>
	{%endblock%}
	</div>

</body>
</html>

userpassword/templates/uspa/index.html
<!DOCTYPE html>
{%extends "uspa/base.html"%}

{%block body_block%}
<div class="jumbotron">
	<h1>HEY Welcome to my registration site</h1>
</div>
{%endblock%}

userpassword/templates/uspa/login.html
<!DOCTYPE html>
{%extends "uspa/base.html"%}
{%block body_block%}
<h1>Please login</h1>
<form action="{%url 'uspa:user_login'%}" method="POST">
	{%csrf_token%}

	<label for="username">Username:</label>
	<input type="text" name="username" placeholder="Enter username"> 


	<label for="password">Password:</label>
	<input type="password" name="password">


	<input type="submit" name="" value="login">



</form>

{%endblock%}